
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Address
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn AddressTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn AlternateName
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Applicant
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantDisability
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantDisabilityCode
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantEmployment
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantEmploymentCode
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantLocation
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantPosition
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ApplicantStatus
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Application
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn CaseCodeTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ConsiderationTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn DisabilityTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Document
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn DocumentTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Education
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn EmergencyContact
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn EmploymentTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn EthnicityTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn GenderTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Interview
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn LocationTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Note
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn NoteTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn OwnerTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Phone
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn PhoneTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn PositionTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn PreviousEmployer
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn QuestionTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Reference
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn SectionTaskCodeTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn ServiceRecord
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn Site
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn SpecialtyCodes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn StateTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn StatusTypes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn TitleCodes
start node %~dp0\server\bin\discover-schema.js -ds Applications -sn vi_ApplicantSearch

