
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Address
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn AddressTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn AlternateName
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Applicant
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn ApplicantLocation
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn ApplicantPosition
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn ApplicantStatus
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Application
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn CaseCodeTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn ConsiderationTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Document
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn DocumentTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Education
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn EmergencyContact
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn EthnicityTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn GenderTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Interview
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn LocationTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Note
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn NoteTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn OwnerTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Phone
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn PhoneTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn PositionTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn PreviousEmployer
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn QuestionTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Reference
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn SectionTaskCodeTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn ServiceRecord
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn Site
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn SpecialtyCodeTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn StatusTypes
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn vi_ApplicantSearch
start node C:\Users\pdelosreyes\source\repos\JobOptions\Node\ORM\JobOptionsApi\server\bin\discover-schema.js -ds Applications -sn vi_Applicant
