/*
*   SSMA warning messages:
*   A2SS0030: View 'ACTIVE LAST CHECK' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[ACTIVE LAST CHECK]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT TOP 9223372036854775807 WITH TIES 
      [upr30100].[EMPLOYID], 
      [upr00100].[INACTIVE], 
      Max([upr30100].[CHEKDATE]) AS MaxOfCHEKDATE, 
      [upr00100].[LASTNAME], 
      [upr00100].[FRSTNAME]
   FROM 
      [upr30100] 
         INNER JOIN [upr00100] 
         ON [upr30100].[EMPLOYID] = [upr00100].[EMPLOYID]
   GROUP BY [upr30100].[EMPLOYID], [upr00100].[INACTIVE], [upr00100].[LASTNAME], [upr00100].[FRSTNAME]
   HAVING ((([upr00100].[INACTIVE]) = 0))
   ORDER BY Max([upr30100].[CHEKDATE])
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[ACTIVE LAST CHECK]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'ACTIVE LAST CHECK';

