/*
*   SSMA warning messages:
*   A2SS0030: View 'cc address' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[cc address]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [RM00102].[ADRSCODE], 
      [RM00102].[CUSTNMBR], 
      [RM00102].[ADDRESS1], 
      [RM00102].[ADDRESS2], 
      [RM00102].[ADDRESS3], 
      [RM00102].[CITY], 
      [RM00102].[STATE], 
      [RM00102].[ZIP], 
      [RM00102].[CNTCPRSN]
   FROM [RM00102]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Make Em Pay.[cc address]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'cc address';

