/*
*   SSMA warning messages:
*   A2SS0030: View 'Check Details' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[Check Details]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [UPR30300].[PYADNMBR], 
      [UPR30300].[DEPRTMNT] AS Department, 
      [UPR30300].[JOBTITLE] AS [Job Title], 
      [UPR30300].[PAYROLCD] AS Paycode, 
      [UPR30300].[UNTSTOPY] AS Units, 
      [UPR30300].[PAYRATE] AS Payrate, 
      [UPR30300].[UPRTRXAM] AS Total, 
      [UPR30300].[STATECD], 
      [UPR30300].[LOCALTAX], 
      [UPR30300].[WRKRCOMP], 
      [UPR30300].[LASTUSER] AS [User], 
      [UPR30300].[SUTASTAT] AS [Suta State], 
      [UPR30300].[CHEKNMBR]
   FROM [UPR30300]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[Check Details]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Check Details';

