/*
*   SSMA warning messages:
*   A2SS0030: View 'NISH EXPORT' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[NISH EXPORT]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [DISTRIBUTIONEXPORT].[IVC ID], [DISTRIBUTIONEXPORT].[DISTRIBUTIONS ACCOUNT], Sum([DISTRIBUTIONEXPORT].[CREDIT AMOUNT]) AS [SumOfCREDIT AMOUNT]
   FROM [DISTRIBUTIONEXPORT]
   GROUP BY [DISTRIBUTIONEXPORT].[IVC ID], [DISTRIBUTIONEXPORT].[DISTRIBUTIONS ACCOUNT]
   HAVING ((([DISTRIBUTIONEXPORT].[DISTRIBUTIONS ACCOUNT]) = '0-000-2025-000'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Make Em Pay.[NISH EXPORT]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'NISH EXPORT';

