/*
*   SSMA warning messages:
*   A2SS0030: View 'qryBudgetHrs Query' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[qryBudgetHrs Query]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [tblBudgetHrs].[GLAcct], 
      [tblBudgetHrs].[Description], 
      [tblBudgetHrs].[Paycode], 
      [tblBudgetHrs].[Annual 2009], 
      [tblBudgetHrs].[Oct], 
      [tblBudgetHrs].[Nov], 
      [tblBudgetHrs].[Dec], 
      [tblBudgetHrs].[Jan], 
      [tblBudgetHrs].[Feb], 
      [tblBudgetHrs].[Mar], 
      [tblBudgetHrs].[Apr], 
      [tblBudgetHrs].[May], 
      [tblBudgetHrs].[Jun], 
      [tblBudgetHrs].[Jul], 
      [tblBudgetHrs].[Aug], 
      [tblBudgetHrs].[Sep]
   FROM [tblBudgetHrs]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[qryBudgetHrs Query]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'qryBudgetHrs Query';

