CREATE VIEW dbo.[Query9]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [fica].[Expr1], [Query8].[SumOfCRDTAMNT], [Expr1] - [SumOfCRDTAMNT] AS Expr2, [fica].[AUCTRLCD]
   FROM 
      [Query8] 
         INNER JOIN [fica] 
         ON [Query8].[ORGNTSRC] = [fica].[AUCTRLCD]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[Query9]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Query9';

