/*
*   SSMA warning messages:
*   A2SS0030: View 'UPR30300 Query' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[UPR30300 Query]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [UPR30300].[CMRECNUM], 
      [UPR30300].[AUCTRLCD], 
      [UPR30300].[EMPLOYID], 
      [UPR30300].[CHEKNMBR], 
      [UPR30300].[PYADNMBR], 
      [UPR30300].[YEAR1], 
      [UPR30300].[CHEKDATE], 
      [UPR30300].[DEPRTMNT], 
      [UPR30300].[PYRLRTYP], 
      [UPR30300].[PAYROLCD], 
      [UPR30300].[TRXSORCE], 
      [UPR30300].[DOCTYPE], 
      [UPR30300].[JOBTITLE], 
      [UPR30300].[TRXBEGDT], 
      [UPR30300].[TRXENDDT], 
      [UPR30300].[UNTSTOPY], 
      [UPR30300].[PAYRATE], 
      [UPR30300].[UPRTRXAM], 
      [UPR30300].[TIMETYPE_I], 
      [UPR30300].[TIMEAVAILABLE], 
      [UPR30300].[TipType], 
      [UPR30300].[RECEIPTS], 
      [UPR30300].[PAYADVNC], 
      [UPR30300].[STATECD], 
      [UPR30300].[LOCALTAX], 
      [UPR30300].[WRKRCOMP], 
      [UPR30300].[USWHPSTD], 
      [UPR30300].[LSTDTEDT], 
      [UPR30300].[LASTUSER], 
      [UPR30300].[SHFTCODE], 
      [UPR30300].[SHFTPREM], 
      [UPR30300].[TXBLWAGS], 
      [UPR30300].[DAYSWRDK], 
      [UPR30300].[WKSWRKD], 
      [UPR30300].[SUTASTAT], 
      [UPR30300].[SBJTFUTA], 
      [UPR30300].[BSDONRTE], 
      [UPR30300].[EMPLCLAS], 
      [UPR30300].[DEX_ROW_ID]
   FROM [UPR30300]
   WHERE ((([UPR30300].[PAYROLCD]) = 'lauv32'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[UPR30300 Query]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'UPR30300 Query';

