/*
*   SSMA warning messages:
*   A2SS0030: View 'Workers Comp Summary Codes' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[Workers Comp Summary Codes]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [wccode].[wc] AS [Workers Comp Summary Code], [wccode].[wc tax] AS [Workers Comp Tax Code From GP]
   FROM [wccode]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[Workers Comp Summary Codes]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Workers Comp Summary Codes';

