/*
*   SSMA warning messages:
*   A2SS0030: View 'Employees Query' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[Employees Query]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [Employees].[Emp#], 
      Max([Employees].[Episode]) AS MaxOfEpisode, 
      [Employees].[First], 
      [Employees].[Last], 
      [Employees].[Dept], 
      [Employees].[Status], 
      Max([Employees].[Term_Date]) AS MaxOfTerm_Date, 
      [Employees].[DisForJob]
   FROM [Employees]
   GROUP BY 
      [Employees].[Emp#], 
      [Employees].[First], 
      [Employees].[Last], 
      [Employees].[Dept], 
      [Employees].[Status], 
      [Employees].[DisForJob]
   HAVING ((([Employees].[Status]) = 't') AND ((Max([Employees].[Term_Date])) > CONVERT(DATETIME, '2009-12-31T00:00:00.000', 126)))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'PTSData.[Employees Query]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Employees Query';

