/*
*   SSMA warning messages:
*   A2SS0030: View 'Find duplicates for Applicant01' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[Find duplicates for Applicant01]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT TOP 9223372036854775807 WITH TIES 
      [Applicant01].[idref], 
      [Applicant01].[IDRef3], 
      [Applicant01].[FirstName], 
      [Applicant01].[Disabled], 
      [Applicant01].[LastName]
   FROM [Applicant01]
   WHERE ((([Applicant01].[idref]) IN 
      (
         SELECT [idref]
         FROM [Applicant01]  AS Tmp
         GROUP BY [idref]
         HAVING Count(*) > 1
      )))
   ORDER BY [Applicant01].[idref]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'PTSData.[Find duplicates for Applicant01]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Find duplicates for Applicant01';

