CREATE VIEW dbo.[ACN]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT TOP 9223372036854775807 WITH TIES [upr30100].[AUCTRLCD], [upr30100].[POSTEDDT], [upr30100].[CHEKDATE], [upr30100].[PYADNMBR]
   FROM [upr30100]
   GROUP BY [upr30100].[AUCTRLCD], [upr30100].[POSTEDDT], [upr30100].[CHEKDATE], [upr30100].[PYADNMBR]
   HAVING ((([upr30100].[POSTEDDT]) > CONVERT(DATETIME, '2006-01-01T00:00:00.000', 126)))
   ORDER BY [upr30100].[PYADNMBR]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[ACN]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'ACN';

