CREATE VIEW dbo.[ActEmpWgList]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [upr00100].[EMPLOYID], 
      [upr00100].[LASTNAME], 
      [upr00100].[FRSTNAME], 
      [upr00100].[INACTIVE] AS [upr00100_INACTIVE], 
      [upr00500].[DEDUCTON], 
      [upr00500].[INACTIVE] AS [upr00500_INACTIVE], 
      [upr00500].[DEDNPRCT_1], 
      [upr00500].[DEDLTMAX], 
      [upr00500].[DEDYRMAX], 
      [upr00500].[DEPYPRMX], 
      [upr00500].[DEDCAMNT_1], 
      [site].[Site], 
      [upr00100].[DEPRTMNT], 
      [upr00100].[SOCSCNUM]
   FROM 
      ([upr00100] 
         INNER JOIN [upr00500] 
         ON [upr00100].[EMPLOYID] = [upr00500].[EMPLOYID]) 
         LEFT JOIN [site] 
         ON [upr00100].[DEPRTMNT] = [site].[code]
   WHERE (
      (([upr00100].[INACTIVE]) = 0) AND 
      (([upr00500].[DEDUCTON]) LIKE '%WG%') AND 
      (([upr00500].[INACTIVE]) = 0))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[ActEmpWgList]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'ActEmpWgList';

