CREATE VIEW dbo.[ca]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [upr30300].[CHEKNMBR], [upr30300].[PAYROLCD], [upr30300].[UPRTRXAM]
   FROM [upr30300]
   WHERE ((([upr30300].[PAYROLCD]) = 'ca'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[ca]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'ca';

