CREATE VIEW dbo.[char]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [UPR30100].[EMPLNAME], Sum([UPR30100].[GRWGPRN]) AS SumOfGRWGPRN
   FROM [UPR30100]
   WHERE ((([UPR30100].[CHEKDATE]) > CONVERT(DATETIME, '2005-12-31T00:00:00.000', 126) AND ([UPR30100].[CHEKDATE]) < CONVERT(DATETIME, '2006-04-01T00:00:00.000', 126)))
   GROUP BY [UPR30100].[EMPLNAME]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[char]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'char';

