/*
*   SSMA warning messages:
*   A2SS0030: View 'check period summary' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[check period summary]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      Sum([UPR30100].[GRWGPRN]) AS [Gross Wages], 
      Sum([UPR30100].[FDWDGPRN]) AS [Federal Taxes Withheld], 
      Sum([UPR30100].[FICAMWPR]) AS [Fica Social Security Withheld], 
      Sum([UPR30100].[FCASWPR]) AS [Fica Medicare Withheld], 
      Sum([UPR30100].[NTWPYRN]) AS [Net Wages], 
      Sum([UPR30100].[FDWGPYRN]) AS [Federal Wages], 
      Sum([UPR30100].[FICASSWP]) AS [Fica Soc Sec Wages], 
      Sum([UPR30100].[FICAMWGP]) AS [Fica Medicare Wages], 
      [UPR30100].[CHEKDATE]
   FROM [UPR30100]
   WHERE ((([UPR30100].[POSTEDDT]) <> CONVERT(DATETIME, '2005-07-27T00:00:00.000', 126)) AND (([UPR30100].[EMPLOYID]) <> 'ALIGNMENT' AND ([UPR30100].[EMPLOYID]) <> 'REPRINTED  '))
   GROUP BY [UPR30100].[CHEKDATE]
   HAVING (((Sum([UPR30100].[GRWGPRN])) <> 0) AND (([UPR30100].[CHEKDATE]) > CONVERT(DATETIME, '1990-01-01T00:00:00.000', 126)))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[check period summary]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'check period summary';

