CREATE VIEW dbo.[chekdates]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [UPR30100].[CHEKDATE]
   FROM [UPR30100]
   GROUP BY [UPR30100].[CHEKDATE]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[chekdates]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'chekdates';

