CREATE VIEW dbo.[chkdedtoteach]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [upr10204].[EMPLOYID], 
      [upr10204].[TTLDEDTN], 
      [upr10204].[DEDUCTON], 
      [UPR00500].[DEDNPRCT_1], 
      [UPR00500].[DEPYPRMX], 
      [UPR00500].[DEDCAMNT_1]
   FROM 
      [upr10204] 
         INNER JOIN [UPR00500] 
         ON ([upr10204].[DEDUCTON] = [UPR00500].[DEDUCTON]) AND ([upr10204].[EMPLOYID] = [UPR00500].[EMPLOYID])
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[chkdedtoteach]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'chkdedtoteach';

