CREATE VIEW dbo.[chkdedtot]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [upr10204].[EMPLOYID], Sum([upr10204].[TTLDEDTN]) AS SumOfTTLDEDTN
   FROM [upr10204]
   GROUP BY [upr10204].[EMPLOYID]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[chkdedtot]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'chkdedtot';

