CREATE VIEW dbo.[DistributionErrors]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT Sum([DISTRIBUTIONEXPORT].[DEBIT AMOUNT]) AS Debit, Sum([DISTRIBUTIONEXPORT].[CREDIT AMOUNT]) AS Credit, [ivcexport].[ivc number]
   FROM 
      [ivcexport] 
         INNER JOIN [DISTRIBUTIONEXPORT] 
         ON [ivcexport].[ID] = [DISTRIBUTIONEXPORT].[IVC ID]
   GROUP BY [DISTRIBUTIONEXPORT].[IVC ID], [ivcexport].[ivc number]
   HAVING (((Sum([DEBIT AMOUNT] - [CREDIT AMOUNT])) > 0.005 OR (Sum([DEBIT AMOUNT] - [CREDIT AMOUNT])) < -0.005))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Make Em Pay.[DistributionErrors]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'DistributionErrors';

