CREATE VIEW dbo.[launvendsel]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [RepetetiveExport].[Site]
   FROM 
      [RepetetiveExport] 
         LEFT JOIN [ivcexport] 
         ON [RepetetiveExport].[Site] = [ivcexport].[site]
   WHERE ((([ivcexport].[site]) IS NULL) AND (([RepetetiveExport].[Type]) = 2))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Make Em Pay.[launvendsel]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'launvendsel';

