/*
*   SSMA warning messages:
*   A2SS0030: View 'payroll posting' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[payroll posting]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [upr30401].[AUCTRLCD], 
      [gl00100].[ACTNUMBR_1], 
      [gl00100].[ACTNUMBR_2], 
      [gl00100].[ACTNUMBR_3], 
      [gl00100].[ACTNUMBR_4], 
      Sum([upr30401].[DEBITAMT]) AS SumOfDEBITAMT, 
      Sum([upr30401].[CRDTAMNT]) AS SumOfCRDTAMNT
   FROM 
      [upr30401] 
         INNER JOIN [gl00100] 
         ON [upr30401].[ACTINDX] = [gl00100].[ACTINDX]
   GROUP BY 
      [upr30401].[AUCTRLCD], 
      [gl00100].[ACTNUMBR_1], 
      [gl00100].[ACTNUMBR_2], 
      [gl00100].[ACTNUMBR_3], 
      [gl00100].[ACTNUMBR_4]
   HAVING ((([upr30401].[AUCTRLCD]) = 'uprcc00001530'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[payroll posting]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'payroll posting';

