/*
*   SSMA warning messages:
*   A2SS0030: View 'Pos Pay Check No' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[Pos Pay Check No]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [UPR30100].[CHEKNMBR]
   FROM 
      [UPR30100] 
         INNER JOIN [pplc] 
         ON [UPR30100].[PYADNMBR] = [pplc].[acn]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[Pos Pay Check No]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Pos Pay Check No';

