CREATE VIEW dbo.[Query8]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [gl20000].[TRXDATE], 
      [gl20000].[ACTINDX], 
      Sum([gl20000].[CRDTAMNT]) AS SumOfCRDTAMNT, 
      [gl20000].[SOURCDOC], 
      [gl20000].[ORGNTSRC]
   FROM [gl20000]
   GROUP BY [gl20000].[TRXDATE], [gl20000].[ACTINDX], [gl20000].[SOURCDOC], [gl20000].[ORGNTSRC]
   HAVING (
      (([gl20000].[TRXDATE]) > CONVERT(DATETIME, '2006-06-30T00:00:00.000', 126) AND ([gl20000].[TRXDATE]) < CONVERT(DATETIME, '2006-08-01T00:00:00.000', 126)) AND 
      (([gl20000].[ACTINDX]) = 252) AND 
      ((Sum([gl20000].[CRDTAMNT])) > 0))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[Query8]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'Query8';

