/*
*   SSMA warning messages:
*   A2SS0030: View 'UPR30100 Query' has a name that might cause problems for the Access application to function correctly against SQL Server.
*/

CREATE VIEW dbo.[UPR30100 Query]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT 
      [UPR30100].[AUCTRLCD], 
      [UPR30100].[CHEKNMBR], 
      [UPR30100].[PYADNMBR], 
      [UPR30100].[VOIDED], 
      [UPR30100].[CHEKDATE], 
      [UPR30100].[POSTEDDT], 
      [UPR30100].[EMPLOYID], 
      [UPR30100].[EMPLNAME], 
      [UPR30100].[GRWGPRN], 
      [UPR30100].[FDWDGPRN], 
      [UPR30100].[FDTXTIPS], 
      [UPR30100].[FICAMWPR], 
      [UPR30100].[FICMTPTX], 
      [UPR30100].[Uncollected_FICAMed_TaxP], 
      [UPR30100].[FCASWPR], 
      [UPR30100].[FICSTPTX], 
      [UPR30100].[Uncollected_FICASS_TaxP], 
      [UPR30100].[ADEICPMT], 
      [UPR30100].[Reported_Tips], 
      [UPR30100].[Charged_Tips], 
      [UPR30100].[ALOCTIPS], 
      [UPR30100].[TTLDDTNS], 
      [UPR30100].[TTLBNFTS], 
      [UPR30100].[NTWPYRN], 
      [UPR30100].[CHEKBKID], 
      [UPR30100].[DEPRTMNT], 
      [UPR30100].[SOCSCNUM], 
      [UPR30100].[VACTMACC], 
      [UPR30100].[VACTMLBL], 
      [UPR30100].[VACAVLBL], 
      [UPR30100].[SKTMACCR], 
      [UPR30100].[SKTMLBTY], 
      [UPR30100].[SIKTIMAV], 
      [UPR30100].[TOTLTAXS], 
      [UPR30100].[Voided_by_Void_Checks], 
      [UPR30100].[FDWGPYRN], 
      [UPR30100].[Federal_TipsPay_Run], 
      [UPR30100].[FICASSWP], 
      [UPR30100].[FICASS_TipsPay_Run], 
      [UPR30100].[FICAMWGP], 
      [UPR30100].[FICAMed_TipsPay_Run], 
      [UPR30100].[Reported_Receipts], 
      [UPR30100].[Charged_Receipts], 
      [UPR30100].[YEAR1], 
      [UPR30100].[ISCHECK], 
      [UPR30100].[RSNCHKVD], 
      [UPR30100].[COMPPYRN], 
      [UPR30100].[DEX_ROW_ID]
   FROM [UPR30100]
   WHERE ((([UPR30100].[CHEKNMBR]) > '272066' AND ([UPR30100].[CHEKNMBR]) < '272228'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[UPR30100 Query]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'UPR30100 Query';

