CREATE VIEW dbo.[wgtotal]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.8.0.*/
   SELECT [upr30300].[EMPLOYID], [upr30300].[PAYROLCD], Sum([upr30300].[UPRTRXAM]) AS SumOfUPRTRXAM
   FROM [upr30300]
   GROUP BY [upr30300].[EMPLOYID], [upr30300].[PAYROLCD]
   HAVING ((([upr30300].[PAYROLCD]) LIKE '%wg%'))
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'Garnish master.[wgtotal]', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'wgtotal';

