CREATE TABLE [dbo].[Applicant011] (
    [idref]              INT              IDENTITY (1, 1) NOT NULL,
    [IDRef3]             NVARCHAR (50)    NULL,
    [FirstName]          NVARCHAR (20)    NULL,
    [Disabled]           BIT              DEFAULT ((0)) NULL,
    [LastName]           NVARCHAR (20)    NULL,
    [DateOfContact]      NVARCHAR (19)    NULL,
    [ContactType]        INT              NULL,
    [ReferringAgency]    NVARCHAR (50)    NULL,
    [DFJDocRecd]         NVARCHAR (19)    NULL,
    [DFJDocRevd]         NVARCHAR (19)    NULL,
    [ApptDate]           NVARCHAR (19)    NULL,
    [Gender]             NVARCHAR (1)     NULL,
    [Ethnicity]          NVARCHAR (50)    NULL,
    [Outcome]            INT              NULL,
    [DET]                NVARCHAR (50)    NULL,
    [ID]                 UNIQUEIDENTIFIER NULL,
    [Resume]             VARBINARY (MAX)  NULL,
    [LinkingID]          NVARCHAR (50)    NULL,
    [Notes]              NVARCHAR (MAX)   NULL,
    [TitleSelect01]      NVARCHAR (50)    NULL,
    [TitleSelect02]      NVARCHAR (50)    NULL,
    [DeptSelect01]       NVARCHAR (50)    NULL,
    [Deptselect02]       NVARCHAR (50)    NULL,
    [Deptselect03]       NVARCHAR (50)    NULL,
    [Deptselect04]       NVARCHAR (50)    NULL,
    [ReContact01]        NVARCHAR (200)   NULL,
    [ReContact02]        NVARCHAR (200)   NULL,
    [Telephone]          NVARCHAR (50)    NULL,
    [SocialSecurity #]   NVARCHAR (50)    NULL,
    [Birthdate]          NVARCHAR (19)    NULL,
    [Address]            NVARCHAR (50)    NULL,
    [City]               NVARCHAR (50)    NULL,
    [Zipcode]            NVARCHAR (50)    NULL,
    [EmergenceyContact]  NVARCHAR (50)    NULL,
    [EmergenceyContact#] NVARCHAR (50)    NULL,
    [Interviewed]        BIT              DEFAULT ((0)) NULL,
    [ReferralAgency]     NVARCHAR (255)   NULL,
    [SSMA_TimeStamp]     ROWVERSION       NOT NULL,
    CONSTRAINT [Applicant011$Applicant01$PrimaryKey] PRIMARY KEY CLUSTERED ([idref] ASC),
    CONSTRAINT [SSMA_CC$Applicant011$Address$disallow_zero_length] CHECK (len([Address])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$ApptDate$disallow_zero_length] CHECK (len([ApptDate])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Birthdate$disallow_zero_length] CHECK (len([Birthdate])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$City$disallow_zero_length] CHECK (len([City])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$DateOfContact$disallow_zero_length] CHECK (len([DateOfContact])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$DeptSelect01$disallow_zero_length] CHECK (len([DeptSelect01])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Deptselect02$disallow_zero_length] CHECK (len([Deptselect02])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Deptselect03$disallow_zero_length] CHECK (len([Deptselect03])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Deptselect04$disallow_zero_length] CHECK (len([Deptselect04])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$DET$disallow_zero_length] CHECK (len([DET])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$DFJDocRecd$disallow_zero_length] CHECK (len([DFJDocRecd])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$DFJDocRevd$disallow_zero_length] CHECK (len([DFJDocRevd])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$EmergenceyContact#$disallow_zero_length] CHECK (len([EmergenceyContact#])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$EmergenceyContact$disallow_zero_length] CHECK (len([EmergenceyContact])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Ethnicity$disallow_zero_length] CHECK (len([Ethnicity])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$FirstName$disallow_zero_length] CHECK (len([FirstName])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Gender$disallow_zero_length] CHECK (len([Gender])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$IDRef3$disallow_zero_length] CHECK (len([IDRef3])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$LastName$disallow_zero_length] CHECK (len([LastName])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$LinkingID$disallow_zero_length] CHECK (len([LinkingID])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Notes$disallow_zero_length] CHECK (len([Notes])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$ReContact01$disallow_zero_length] CHECK (len([ReContact01])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$ReContact02$disallow_zero_length] CHECK (len([ReContact02])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$ReferralAgency$disallow_zero_length] CHECK (len([ReferralAgency])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$ReferringAgency$disallow_zero_length] CHECK (len([ReferringAgency])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$SocialSecurity #$disallow_zero_length] CHECK (len([SocialSecurity #])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Telephone$disallow_zero_length] CHECK (len([Telephone])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$TitleSelect01$disallow_zero_length] CHECK (len([TitleSelect01])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$TitleSelect02$disallow_zero_length] CHECK (len([TitleSelect02])>(0)),
    CONSTRAINT [SSMA_CC$Applicant011$Zipcode$disallow_zero_length] CHECK (len([Zipcode])>(0))
);

