CREATE TABLE [dbo].[Applicant] (
    [idref]              INT              NOT NULL,
    [IDRef3]             NVARCHAR (50)    NULL,
    [FirstName]          NVARCHAR (20)    NULL,
    [Disabled]           BIT              NULL,
    [LastName]           NVARCHAR (20)    NULL,
    [DateOfContact]      DATETIME2 (7)    NULL,
    [ContactType]        INT              NULL,
    [ReferringAgency]    NVARCHAR (50)    NULL,
    [DFJDocRecd]         DATETIME2 (7)    NULL,
    [DFJDocRevd]         DATETIME2 (7)    NULL,
    [ApptDate]           DATETIME2 (7)    NULL,
    [Gender]             NVARCHAR (1)     NULL,
    [Ethnicity]          NVARCHAR (50)    NULL,
    [Outcome]            INT              NULL,
    [DET]                NVARCHAR (50)    NULL,
    [ID]                 UNIQUEIDENTIFIER NULL,
    [Resume]             VARBINARY (MAX)  NULL,
    [LinkingID]          NVARCHAR (50)    NULL,
    [Notes]              NVARCHAR (MAX)   NULL,
    [TitleSelect01]      NVARCHAR (50)    NULL,
    [TitleSelect02]      NVARCHAR (50)    NULL,
    [DeptSelect01]       NVARCHAR (50)    NULL,
    [Deptselect02]       NVARCHAR (50)    NULL,
    [Deptselect03]       NVARCHAR (50)    NULL,
    [Deptselect04]       NVARCHAR (50)    NULL,
    [ReContact01]        NVARCHAR (200)   NULL,
    [ReContact02]        NVARCHAR (200)   NULL,
    [Telephone]          NVARCHAR (50)    NULL,
    [SocialSecurity #]   NVARCHAR (50)    NULL,
    [Birthdate]          DATETIME2 (7)    NULL,
    [Address]            NVARCHAR (50)    NULL,
    [City]               NVARCHAR (50)    NULL,
    [Zipcode]            NVARCHAR (50)    NULL,
    [EmergenceyContact]  NVARCHAR (50)    NULL,
    [EmergenceyContact#] NVARCHAR (50)    NULL,
    [Interviewed]        BIT              NULL,
    [ReferralAgency]     NVARCHAR (255)   NULL,
    [SSMA_TimeStamp]     ROWVERSION       NOT NULL,
    [CreateDate]         DATETIME2 (3)    DEFAULT (getutcdate()) NOT NULL,
    [CreateUser]         VARCHAR (128)    DEFAULT (suser_sname()) NOT NULL,
    [ModifyDate]         DATETIME2 (3)    DEFAULT (getutcdate()) NOT NULL,
    [ModifyUser]         VARCHAR (128)    DEFAULT (suser_sname()) NOT NULL,
    [MiddleName]         NVARCHAR (1)     NULL
);



