CREATE TABLE [dbo].[Employee] (
    [Emp#]                    FLOAT (53)     NOT NULL,
    [Episode]                 INT            NULL,
    [SS]                      NVARCHAR (12)  NOT NULL,
    [First]                   NVARCHAR (20)  NULL,
    [Middle]                  NVARCHAR (20)  NULL,
    [Last]                    NVARCHAR (20)  NULL,
    [Dept]                    NVARCHAR (3)   NULL,
    [Job_Title]               NVARCHAR (20)  NULL,
    [MultiTitle]              NVARCHAR (2)   NULL,
    [Status]                  NVARCHAR (1)   NULL,
    [ReferringAgency]         NVARCHAR (40)  NULL,
    [Sex]                     NVARCHAR (1)   NOT NULL,
    [Birthdate]               DATETIME2 (7)  NULL,
    [Ethnicity]               NVARCHAR (20)  NOT NULL,
    [EEO_Code]                NVARCHAR (15)  NOT NULL,
    [EEO_DIVX]                NVARCHAR (6)   NULL,
    [Vets_100]                NVARCHAR (6)   NULL,
    [Hire_Date]               DATETIME2 (7)  NULL,
    [BaseWage]                FLOAT (53)     NULL,
    [SalariedExempt]          NVARCHAR (1)   NOT NULL,
    [DIS]                     NVARCHAR (1)   NULL,
    [DisType]                 NVARCHAR (20)  NULL,
    [DisForJob]               NVARCHAR (1)   NOT NULL,
    [SpecialProductivity]     FLOAT (53)     NULL,
    [SpecialProductivityDate] DATETIME2 (7)  NULL,
    [Ins_Carrie]              NVARCHAR (20)  NULL,
    [Term_Date]               DATETIME2 (7)  NULL,
    [Term_Reason]             NVARCHAR (50)  NULL,
    [DayNight]                NVARCHAR (1)   NULL,
    [#]                       INT            NOT NULL,
    [DataEntryDateAndTime]    DATETIME2 (7)  NULL,
    [LastDayWorked]           DATETIME2 (7)  NULL,
    [IdProvided]              NVARCHAR (10)  NULL,
    [IDNumber]                NVARCHAR (15)  NULL,
    [FedTaxStatus]            NVARCHAR (10)  NULL,
    [FedTaxExemptions]        INT            NULL,
    [StateTaxStatus]          NVARCHAR (50)  NULL,
    [StateTaxExemptions]      INT            NULL,
    [EmergencyContact]        NVARCHAR (30)  NULL,
    [EmergencyAddy1]          NVARCHAR (31)  NULL,
    [EmergencyAddy2]          NVARCHAR (31)  NULL,
    [EmergencyCity]           NVARCHAR (15)  NULL,
    [EmergencyState]          NVARCHAR (2)   NULL,
    [EmergencyZip]            INT            NULL,
    [Marrital Status]         NVARCHAR (50)  NULL,
    [Memo]                    NVARCHAR (MAX) NULL,
    [I9Status]                SMALLINT       NULL,
    [RenewDate]               DATETIME2 (7)  NULL,
    [EvaluationRenewalDate]   DATETIME2 (7)  NULL,
    [ResetERD]                BIT            NULL,
    [30DayEvaluation]         BIT            NULL,
    [ProductivityRenewalDate] DATETIME2 (7)  NULL,
    [30DayProductivity]       BIT            NULL,
    [ResetProductivity]       BIT            NULL,
    [JoppEmp]                 BIT            NULL,
    [DefaultJobCode]          NVARCHAR (25)  NULL,
    [AddlIns]                 BIT            NULL,
    [Benefit]                 BIT            NULL,
    [LOA]                     BIT            NULL,
    [WC]                      BIT            NULL,
    [Conservatorship]         BIT            NULL,
    [LOA2]                    BIT            NULL,
    [WC2]                     BIT            NULL,
    [SSMA_TimeStamp]          ROWVERSION     NOT NULL,
    [CreateDate]              DATETIME2 (3)  DEFAULT (getutcdate()) NOT NULL,
    [CreateUser]              VARCHAR (128)  DEFAULT (suser_sname()) NOT NULL,
    [ModifyDate]              DATETIME2 (3)  DEFAULT (getutcdate()) NOT NULL,
    [ModifyUser]              VARCHAR (128)  DEFAULT (suser_sname()) NOT NULL
);

